/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * cels-cli App Header
 *
 * Root composition, renderer init, and CEL_Build for the CLI TUI shell.
 * main.c calls CELS_BuildInit() (generated by CEL_Build in app.c)
 * and the Engine lifecycle functions.
 */

#ifndef CELS_CLI_APP_H
#define CELS_CLI_APP_H

#include <cels/cels.h>

/* CELS_BuildInit() is declared in cels.h as:
 *   extern void CELS_BuildInit(void);
 * It is generated by CEL_Build(CelsCLI) in app.c.
 * main.c calls it after Engine_Startup(). */

#endif /* CELS_CLI_APP_H */
