/*
 * cels-cli App Header
 *
 * Root composition, renderer init, and CEL_Build for the CLI TUI shell.
 * main.c calls CELS_BuildInit() (generated by CEL_Build in app.c)
 * and the Engine lifecycle functions.
 */

#ifndef CELS_CLI_APP_H
#define CELS_CLI_APP_H

#include <cels/cels.h>

/* CELS_BuildInit() is declared in cels.h as:
 *   extern void CELS_BuildInit(void);
 * It is generated by CEL_Build(CelsCLI) in app.c.
 * main.c calls it after Engine_Startup(). */

#endif /* CELS_CLI_APP_H */
